---
# Self-signed ClusterIssuer for local testing
# This creates certificates that browsers will warn about, but good for lab
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# Let's Encrypt Staging Issuer (for testing without rate limits)
# Replace email with your own
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # ACME server URL for Let's Encrypt staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email for certificate expiration notifications
    email: your-email@example.com  # CHANGE THIS
    # Private key for ACME account
    privateKeySecretRef:
      name: letsencrypt-staging
    # Use HTTP-01 challenge (works with most setups)
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Let's Encrypt Production Issuer (use after testing with staging)
# Replace email with your own
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # ACME server URL for Let's Encrypt production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for certificate expiration notifications
    email: your-email@example.com  # CHANGE THIS
    # Private key for ACME account
    privateKeySecretRef:
      name: letsencrypt-prod
    # Use HTTP-01 challenge
    solvers:
    - http01:
        ingress:
          class: nginx
