---
# k6-operator ArgoCD Application
# Deploys the Grafana k6-operator for running distributed load tests
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: k6-operator
      targetRevision: 3.16.0
      helm:
        releaseName: k6-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: k6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
