# ArgoCD Image Updater
#
# Watches container registries for new image tags and updates
# ArgoCD Applications automatically. Keeps CI decoupled from GitOps.
#
# Write-back mode: git (commits to repo for full audit trail)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
    environment: kind
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater
      targetRevision: 0.11.0
      helm:
        valueFiles:
          - $values/platform/values/argocd-image-updater.yaml
    - repoURL: https://github.com/illMadeCoder/k8s-ai-testbed.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
