# Argo Workflows for Hub
#
# Experiment orchestration engine. Workflows submitted here
# create orchestrator clusters and run experiments.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
    environment: kind
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      targetRevision: 0.46.2
      helm:
        valueFiles:
          - $values/platform/values/argo-workflows.yaml
    - repoURL: https://github.com/illMadeCoder/k8s-ai-testbed.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
