# Crossplane Providers Base (Wave 2)
# Helm and Kubernetes providers
# Depends on: crossplane-providers-core
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers-base
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/illMadeCoder/illm-k8s-ai-labs.git
    targetRevision: HEAD
    path: platform/manifests/crossplane-providers/base
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
