# Crossplane XRDs for Hub
#
# Cloud abstraction layer — XRDs provide a unified ObjectStorage API
# backed by AWS S3, Azure Blob, or GCP GCS compositions.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-xrds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/illMadeCoder/k8s-ai-cloud-testbed.git
    targetRevision: HEAD
    path: platform/manifests/crossplane-xrds/definitions
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  ignoreDifferences:
    - group: apiextensions.crossplane.io
      kind: CompositeResourceDefinition
      jqPathExpressions:
        - .status
    - group: apiextensions.crossplane.io
      kind: Composition
      jqPathExpressions:
        - .status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
