# Grafana for Hub
#
# Visualization and dashboards for the LGTM observability stack.
# Pre-configured with Loki, Mimir, and Tempo data sources.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
    environment: talos
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # After observability backends (wave 3)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.5
      helm:
        valueFiles:
          - $values/platform/values/grafana.yaml
    - repoURL: https://github.com/illMadeCoder/k8s-ai-testbed.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
