# Headlamp - Kubernetes Dashboard UI
#
# Web UI for browsing and managing cluster resources.
# Exposed via Tailscale ingress for secure remote access.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
    environment: talos
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.39.0
      helm:
        valueFiles:
          - $values/platform/values/headlamp.yaml
    - repoURL: https://github.com/illMadeCoder/illm-k8s-ai-labs.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
