# SeaweedFS for Hub
#
# S3-compatible object storage for the observability stack.
# Provides storage backend for Loki, Mimir, and Tempo.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
    environment: talos
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy early, before observability
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://seaweedfs.github.io/seaweedfs/helm
      chart: seaweedfs
      targetRevision: 4.0.0
      helm:
        valueFiles:
          - $values/platform/values/seaweedfs.yaml
    - repoURL: https://github.com/illMadeCoder/k8s-ai-testbed.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.spec.volumeMode
        - .spec.volumeClaimTemplates[]?.apiVersion
        - .spec.volumeClaimTemplates[]?.kind
        - .spec.volumeClaimTemplates[]?.status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
