# ELK Logging Stack
# Deploys: ECK Operator + ELK Stack (Elasticsearch, Kibana, Filebeat)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-elk
  namespace: argocd
  labels:
    layer: stack
    stack: elk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Logs - ECK Operator (manages Elasticsearch)
    - repoURL: https://github.com/illMadeCoder/illm-k8s-ai-labs.git
      targetRevision: HEAD
      path: components/observability/eck-operator
      directory:
        recurse: false
        include: 'eck-operator.yaml'

    # Logs - ELK Stack (Elasticsearch, Kibana, Filebeat)
    - repoURL: https://github.com/illMadeCoder/illm-k8s-ai-labs.git
      targetRevision: HEAD
      path: components/observability/elk-stack
      directory:
        recurse: false
        include: 'elk-stack.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
