# Webhook Relay (smee-client)
#
# Relays GitHub webhooks from smee.io to ArgoCD for instant sync.
# Required for local clusters without public ingress.
#
# Setup:
#   1. Go to https://smee.io/new in browser
#   2. Update manifests/webhook-relay/kustomization.yaml with the URL
#   3. Configure GitHub webhook to point to smee.io URL
#
# Uses Kustomize for environment-specific smee.io channel URL.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook-relay
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
    environment: kind
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/illMadeCoder/k8s-ai-cloud-testbed.git
    targetRevision: HEAD
    path: platform/manifests/webhook-relay
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
