---
# Backstage Service Catalog - Auto-discovered Services
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: k8s-lab
  title: Kubernetes Lab Cluster
spec:
  owner: user:admin
  description: All services running on the lab Kubernetes cluster

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-app
  title: Demo Application
  annotations:
    kubernetes.io/service-name: demo-app
    kubernetes.io/namespace: default
spec:
  type: service
  lifecycle: production
  system: k8s-lab
  owner: user:admin
  description: Demo application running on the cluster
  links:
    - url: http://192.168.49.2:30001
      title: Demo App Access
      icon: dashboard

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd
  title: ArgoCD GitOps
  annotations:
    kubernetes.io/service-name: argocd-server
    kubernetes.io/namespace: argocd
spec:
  type: service
  lifecycle: production
  system: k8s-lab
  owner: user:admin
  description: ArgoCD continuous deployment platform
  links:
    - url: https://192.168.49.2:30443
      title: ArgoCD UI
      icon: dashboard

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  title: Grafana Observability
  annotations:
    kubernetes.io/service-name: kube-prometheus-stack-grafana
    kubernetes.io/namespace: observability
spec:
  type: service
  lifecycle: production
  system: k8s-lab
  owner: user:admin
  description: Grafana metrics visualization platform
  links:
    - url: http://192.168.49.2:30300
      title: Grafana Dashboards
      icon: monitoring
  dependencies:
    - prometheus

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus
  title: Prometheus Monitoring
  annotations:
    kubernetes.io/service-name: kube-prometheus-stack-prometheus
    kubernetes.io/namespace: observability
spec:
  type: service
  lifecycle: production
  system: k8s-lab
  owner: user:admin
  description: Prometheus metrics collection and storage
  links:
    - url: http://192.168.49.2:30090
      title: Prometheus API
      icon: monitoring

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  title: Backstage Service Catalog
  annotations:
    kubernetes.io/service-name: backstage
    kubernetes.io/namespace: backstage
spec:
  type: service
  lifecycle: production
  system: k8s-lab
  owner: user:admin
  description: Service discovery and development portal
  links:
    - url: http://192.168.49.2:30540
      title: Backstage Portal
      icon: dashboard

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vault
  title: Vault Secrets Management
  annotations:
    kubernetes.io/service-name: vault
    kubernetes.io/namespace: vault
spec:
  type: service
  lifecycle: production
  system: k8s-lab
  owner: user:admin
  description: HashiCorp Vault for secrets management
  links:
    - url: http://192.168.49.2:30200
      title: Vault UI
      icon: security

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: envoy-gateway
  title: Envoy Gateway
  annotations:
    kubernetes.io/service-name: envoy-default-lab-gateway-cb012393
    kubernetes.io/namespace: envoy-gateway-system
spec:
  type: service
  lifecycle: production
  system: k8s-lab
  owner: user:admin
  description: Modern ingress controller with Gateway API
  links:
    - url: http://192.168.49.2:8080
      title: Gateway HTTP
      icon: router
