version: '3'

silent: true

includes:
  hub: ./platform/hub/cluster/Taskfile.yaml
  talos: ./platform/hub/Taskfile.talos-bootstrap.yaml
  talos-hub: ./platform/hub/Taskfile.talos-hub.yaml

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
