version: '3'

silent: true

includes:
  kind: ./platforms/kind/Taskfile.yaml
  talos: ./platforms/talos/Taskfile.yaml
  # cloud: ./platforms/cloud/Taskfile.yaml  # future

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
