version: '3'

silent: true

includes:
  kind: ./kind/Taskfile.yaml
  # talos: ./talos/Taskfile.yaml  # future
  # cloud: ./cloud/Taskfile.yaml  # future

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
