version: '3'

silent: true

includes:
  hub: ./platform/hub/cluster/Taskfile.yaml
  talos: ./platform/targets/talos/cluster/Taskfile.yaml
  talos-hub: ./platform/hub-talos/Taskfile.yaml
  # cloud: ./platform/targets/cloud/cluster/Taskfile.yaml  # future

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
