apiVersion: experiments.illm.io/v1alpha1
kind: Component
metadata:
  name: station-monitor
spec:
  type: app
  description: "Station monitoring app for Prometheus tutorial (Sector 12 mystery)"
  sources:
    - repoURL: https://github.com/illMadeCoder/k8s-ai-cloud-testbed.git
      targetRevision: HEAD
      path: components/apps/station-monitor/k8s
  observability:
    serviceMonitor: true
    podLabels:
      app: station-monitor
    metricsPort: 8080
