apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
    targetRevision: HEAD
    path: argocd-apps/k6
  destination:
    server: https://kubernetes.default.svc
    namespace: k6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
