apiVersion: experiments.illm.io/v1alpha1
kind: Component
metadata:
  name: loki
spec:
  type: app
  description: "Loki log aggregation system via Grafana Helm chart"
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: "6.28.0"
      chart: loki
      helm:
        releaseName: loki
        parameters:
          - name: deploymentMode
            value: SingleBinary
          - name: loki.auth_enabled
            value: "false"
          - name: loki.commonConfig.replication_factor
            value: "1"
          - name: loki.storage.type
            value: filesystem
          - name: loki.schemaConfig.configs[0].from
            value: "2024-01-01"
          - name: loki.schemaConfig.configs[0].store
            value: tsdb
          - name: loki.schemaConfig.configs[0].object_store
            value: filesystem
          - name: loki.schemaConfig.configs[0].schema
            value: v13
          - name: loki.schemaConfig.configs[0].index.prefix
            value: loki_index_
          - name: loki.schemaConfig.configs[0].index.period
            value: 24h
          - name: singleBinary.replicas
            value: "1"
          - name: singleBinary.persistence.storageClass
            value: local-path
          - name: read.replicas
            value: "0"
          - name: write.replicas
            value: "0"
          - name: backend.replicas
            value: "0"
          - name: chunksCache.enabled
            value: "false"
          - name: resultsCache.enabled
            value: "false"
  parameters:
    - name: loki.auth_enabled
      type: bool
      default: "false"
      description: "Enable multi-tenancy authentication"
    - name: singleBinary.replicas
      type: int
      default: "1"
      description: "Number of Loki single-binary replicas"
  observability:
    serviceMonitor: true
    podLabels:
      app.kubernetes.io/name: loki
