# Pyrra - SLO Management for Kubernetes
# Generates recording rules and multi-burn-rate alerts from SLO specs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyrra
  namespace: argocd
  labels:
    component: observability
    tier: slo
spec:
  project: default
  source:
    repoURL: https://rlex.github.io/helm-charts
    chart: pyrra
    targetRevision: 0.12.0
    helm:
      releaseName: pyrra
      valueFiles:
        - $values/components/observability/pyrra/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pyrra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
