# Crossplane for Hub
#
# Infrastructure-as-code engine. Provisions cloud resources
# (AKS, EKS, databases, etc.) for experiment clusters.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
    environment: kind
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 1.18.1
      helm:
        valueFiles:
          - $values/hub/app-of-apps/kind/values/crossplane.yaml
    - repoURL: https://github.com/illMadeCoder/illm-k8s-ai-labs.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
