# MetalLB for Kind
#
# Provides LoadBalancer capability for Kind clusters.
# Assigns IPs from a configured range on the Kind docker network.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
    environment: kind
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before other apps need LoadBalancer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.14.9
      helm:
        valueFiles:
          - $values/hub/app-of-apps/kind/values/metallb.yaml
    - repoURL: https://github.com/illMadeCoder/illm-k8s-ai-labs.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  ignoreDifferences:
    # CRDs get status/metadata fields added by Kubernetes
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
        - /metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
