apiVersion: experiments.illm.io/v1alpha1
kind: Component
metadata:
  name: mimir
spec:
  type: app
  description: "Grafana Mimir TSDB in monolithic mode (single binary, all components)"
  sources:
    - repoURL: https://github.com/illMadeCoder/k8s-ai-cloud-testbed.git
      targetRevision: HEAD
      path: components/observability/mimir/k8s
  observability:
    serviceMonitor: false
    podLabels:
      app.kubernetes.io/name: mimir
