---
# Queue CompositeResourceDefinition
# Provides a cloud-agnostic API for message queues
# Compositions implement Azure Service Bus and AWS SQS
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xqueues.illm.io
spec:
  group: illm.io
  names:
    kind: XQueue
    plural: xqueues
  claimNames:
    kind: Queue
    plural: queues
  connectionSecretKeys:
    - endpoint
    - queueUrl
    - accessKey
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                  description: Queue type
                  enum:
                    - standard
                    - fifo
                  default: standard
                messageRetentionDays:
                  type: integer
                  description: Message retention period in days
                  default: 4
                  minimum: 1
                  maximum: 14
                visibilityTimeoutSeconds:
                  type: integer
                  description: Visibility timeout in seconds
                  default: 30
                  minimum: 0
                  maximum: 43200
                deadLetterQueue:
                  type: boolean
                  description: Enable dead letter queue
                  default: false
                encryption:
                  type: boolean
                  description: Enable encryption at rest
                  default: true
            status:
              type: object
              properties:
                endpoint:
                  type: string
                  description: Queue endpoint/URL
                queueName:
                  type: string
                  description: Actual queue name
                cloud:
                  type: string
                  description: Cloud provider
      additionalPrinterColumns:
        - name: Type
          type: string
          jsonPath: .spec.type
        - name: Endpoint
          type: string
          jsonPath: .status.endpoint
        - name: Cloud
          type: string
          jsonPath: .status.cloud
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
