---
# Azure Composition for Database XRD
# Creates Azure PostgreSQL/MySQL Flexible Server
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdatabases.azure.illm.io
  labels:
    provider: azure
    crossplane.io/xrd: xdatabases.illm.io
spec:
  compositeTypeRef:
    apiVersion: illm.io/v1alpha1
    kind: XDatabase

  # Use EnvironmentConfig for automatic cloud selection
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: cluster-info

  patchSets:
    - name: common-tags
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true

  resources:
    # Resource Group for database resources
    - name: resource-group
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        spec:
          forProvider:
            location: eastus
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-db-rg"
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.name
          transforms:
            - type: string
              string:
                fmt: "%s-db-rg"

    # PostgreSQL Flexible Server
    - name: postgresql-server
      base:
        apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
        kind: FlexibleServer
        spec:
          forProvider:
            location: eastus
            administratorLogin: dbadmin
            administratorPasswordSecretRef:
              key: password
              namespace: crossplane-system
            version: "14"
            storageMb: 32768
            skuName: B_Standard_B1ms
            publicNetworkAccessEnabled: false
            geoRedundantBackupEnabled: false
            resourceGroupNameSelector:
              matchControllerRef: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        # Name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.name

        # Version
        - type: FromCompositeFieldPath
          fromFieldPath: spec.version
          toFieldPath: spec.forProvider.version

        # Size mapping: abstract size -> Azure SKU
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.forProvider.skuName
          transforms:
            - type: map
              map:
                small: B_Standard_B1ms
                medium: GP_Standard_D2s_v3
                large: GP_Standard_D4s_v3

        # Storage: GB -> MB
        - type: FromCompositeFieldPath
          fromFieldPath: spec.storageGB
          toFieldPath: spec.forProvider.storageMb
          transforms:
            - type: math
              math:
                multiply: 1024

        # Public access
        - type: FromCompositeFieldPath
          fromFieldPath: spec.publicAccess
          toFieldPath: spec.forProvider.publicNetworkAccessEnabled

        # High availability
        - type: FromCompositeFieldPath
          fromFieldPath: spec.highAvailability
          toFieldPath: spec.forProvider.highAvailability[0].mode
          transforms:
            - type: map
              map:
                "true": ZoneRedundant
                "false": Disabled

        # Backup retention
        - type: FromCompositeFieldPath
          fromFieldPath: spec.backupRetentionDays
          toFieldPath: spec.forProvider.backupRetentionDays

        # Connection secret name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-db-conn"

        # Status: endpoint
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.fqdn
          toFieldPath: status.endpoint

        # Status: cloud
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: status.cloud
          transforms:
            - type: string
              string:
                fmt: azure

    # Firewall rule for public access (if enabled)
    - name: firewall-rule
      base:
        apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
        kind: FlexibleServerFirewallRule
        spec:
          forProvider:
            startIpAddress: "0.0.0.0"
            endIpAddress: "255.255.255.255"
            serverIdSelector:
              matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-allow-all"
        # Only create if publicAccess is true
        - type: FromCompositeFieldPath
          fromFieldPath: spec.publicAccess
          toFieldPath: metadata.annotations[crossplane.io/external-create-pending]
          transforms:
            - type: convert
              convert:
                toType: string

    # Database inside the server
    - name: database
      base:
        apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
        kind: FlexibleServerDatabase
        spec:
          forProvider:
            charset: UTF8
            collation: en_US.utf8
            serverIdSelector:
              matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-db"
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.name
