---
# Database CompositeResourceDefinition
# Provides a cloud-agnostic API for relational databases
# Compositions implement Azure PostgreSQL/MySQL and AWS RDS
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.illm.io
spec:
  group: illm.io
  names:
    kind: XDatabase
    plural: xdatabases
  claimNames:
    kind: Database
    plural: databases
  connectionSecretKeys:
    - host
    - port
    - username
    - password
    - database
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - engine
                - size
              properties:
                engine:
                  type: string
                  description: Database engine type
                  enum:
                    - postgresql
                    - mysql
                  default: postgresql
                version:
                  type: string
                  description: Engine version (e.g., "14", "15" for PostgreSQL)
                  default: "14"
                size:
                  type: string
                  description: Instance size class (abstract - maps to cloud-specific SKUs)
                  enum:
                    - small
                    - medium
                    - large
                  default: small
                storageGB:
                  type: integer
                  description: Storage size in GB
                  default: 20
                  minimum: 10
                  maximum: 1000
                publicAccess:
                  type: boolean
                  description: Enable public network access (not recommended for production)
                  default: false
                highAvailability:
                  type: boolean
                  description: Enable high availability (zone redundant)
                  default: false
                backupRetentionDays:
                  type: integer
                  description: Backup retention period in days
                  default: 7
                  minimum: 1
                  maximum: 35
            status:
              type: object
              properties:
                endpoint:
                  type: string
                  description: Database connection endpoint
                port:
                  type: integer
                  description: Database port
                status:
                  type: string
                  description: Current status of the database
                cloud:
                  type: string
                  description: Cloud provider where database is deployed
      additionalPrinterColumns:
        - name: Engine
          type: string
          jsonPath: .spec.engine
        - name: Size
          type: string
          jsonPath: .spec.size
        - name: Storage
          type: integer
          jsonPath: .spec.storageGB
        - name: Endpoint
          type: string
          jsonPath: .status.endpoint
        - name: Cloud
          type: string
          jsonPath: .status.cloud
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
