version: '3'

# Hub Cluster Bootstrap
#
# Usage:
#   task bootstrap:kind    # Full setup (cluster, ArgoCD, DNS)
#   task destroy           # Tear down

silent: true

vars:
  HUB_CLUSTER: hub
  ARGOCD_NAMESPACE: argocd
  DNS_IP: 172.19.255.200

tasks:
  bootstrap:kind:
    desc: Bootstrap hub on Kind (full setup)
    cmds:
      # Create cluster
      - |
        echo "=== Creating Kind cluster ==="
        kind create cluster --name {{.HUB_CLUSTER}} --wait 60s || true
        kubectl config use-context kind-{{.HUB_CLUSTER}}

      # Install ArgoCD
      - |
        echo "=== Installing ArgoCD ==="
        helm repo add argo https://argoproj.github.io/argo-helm 2>/dev/null || true
        helm repo update argo
        helm upgrade --install argocd argo/argo-cd \
          -n {{.ARGOCD_NAMESPACE}} --create-namespace \
          -f {{.TASKFILE_DIR}}/bootstrap/argocd-values-kind.yaml

      # Apply hub application
      - |
        echo "=== Applying hub application ==="
        kubectl apply -f {{.TASKFILE_DIR}}/bootstrap/hub-application.yaml

      # Wait for DNS stack
      - |
        echo "=== Waiting for services ==="
        echo "Waiting for dns-stack to be healthy..."
        until kubectl get application dns-stack -n argocd -o jsonpath='{.status.health.status}' 2>/dev/null | grep -q "Healthy"; do
          sleep 5
        done
        echo "dns-stack healthy!"

        echo "Waiting for k8s_gateway LoadBalancer..."
        until kubectl get svc dns-stack-k8s-gateway -n dns-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null | grep -q "{{.DNS_IP}}"; do
          sleep 2
        done
        echo "k8s_gateway ready at {{.DNS_IP}}"

      # Configure host DNS
      - |
        echo "=== Configuring host DNS ==="
        if grep -q "{{.DNS_IP}}" /etc/resolv.conf 2>/dev/null; then
          echo "Already configured"
        else
          if grep -q "nameserver" /etc/resolv.conf; then
            sudo sed -i '0,/nameserver/s/nameserver/nameserver {{.DNS_IP}}\nnameserver/' /etc/resolv.conf
          else
            echo "nameserver {{.DNS_IP}}" | sudo tee -a /etc/resolv.conf
          fi
          echo "DNS configured"
        fi

      # Verify
      - |
        echo ""
        echo "=== Bootstrap Complete ==="
        kubectl get applications -n {{.ARGOCD_NAMESPACE}}
        echo ""
        echo "ArgoCD UI: https://argocd-server.argocd.k8s.local"
        echo "Password:  $(kubectl -n {{.ARGOCD_NAMESPACE}} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)"

  destroy:
    desc: Destroy Kind hub cluster
    cmds:
      - kind delete cluster --name {{.HUB_CLUSTER}}

  # Helper tasks (optional)
  status:
    desc: Show hub status
    cmds:
      - kubectl get applications -n {{.ARGOCD_NAMESPACE}} 2>/dev/null || echo "ArgoCD not installed"

  password:
    desc: Get ArgoCD admin password
    cmds:
      - kubectl -n {{.ARGOCD_NAMESPACE}} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d && echo
